#!/usr/bin/env python3
"""Read-only validation against pure canonical rendering, plus structural checks.

No repair, model execution, source notebook execution, network, or provider call.
The manifest is compared to independently rendered content, not trusted alone.
"""
from __future__ import annotations
import argparse,json,re,sys
from pathlib import Path
sys.dont_write_bytecode=True
from build_pack import PackError,render


def check_markdown(root:Path,path:str,payload:bytes):
    text=payload.decode('utf-8');fence=None;visible=[]
    for line in text.splitlines():
        fm=re.match(r'^\s*(`{3,}|~{3,})',line)
        if fm:
            mark=fm.group(1)
            if fence is None:fence=(mark[0],len(mark))
            elif mark[0]==fence[0] and len(mark)>=fence[1]:fence=None
            continue
        if fence is None:visible.append(line)
    if fence:raise PackError('MARKDOWN_FENCE',path)
    visible='\n'.join(visible)
    anchors=re.findall(r'<a id="([^"]+)"></a>',visible)
    if len(anchors)!=len(set(anchors)):raise PackError('DUPLICATE_ANCHOR',path)
    for dest in re.findall(r'\]\(([^\s)]+)\)',visible):
        if re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:',dest):continue
        filepart,_,anchor=dest.partition('#')
        target=(root/path).parent/filepart if filepart else root/path
        target=target.resolve()
        if not target.is_relative_to(root):raise PackError('LINK_ESCAPE',f'{path}: {dest}')
        if not target.is_file():raise PackError('BROKEN_LINK',f'{path}: {dest}')
        if anchor and f'id="{anchor}"' not in target.read_text(encoding='utf-8'):
            raise PackError('BROKEN_ANCHOR',f'{path}: {dest}')
    if re.search(r'\[\[[A-Z][A-Z0-9-]*\]\]|@@[A-Z_]+@@',visible):raise PackError('UNRESOLVED_TOKEN',path)


def validate(root:Path)->list[str]:
    root=root.resolve();expected=render(root);results=[]
    # Rendered artifacts checked before manifest: refreshed self-reported
    # hashes cannot disguise stale books or matching but incorrect mirrors.
    for path,payload in expected.items():
        if path=='MANIFEST.json':continue
        target=root/path
        if not target.is_file():raise PackError('GENERATED_MISSING',path)
        if target.read_bytes()!=payload:raise PackError('GENERATED_DRIFT',path)
    results.append(f'{len(expected)-1} generated artifacts equal the canonical render byte-for-byte, including both books, pack copies, modules, recipes and loaders.')
    try:actual=json.loads((root/'MANIFEST.json').read_text(encoding='utf-8'))
    except (OSError,ValueError) as exc:raise PackError('MANIFEST_INVALID','MANIFEST.json') from exc
    if actual!=json.loads(expected['MANIFEST.json']):raise PackError('MANIFEST_DRIFT','inventory, input/support hashes, or generated bytes/words/hash metadata differ')
    results.append('Manifest inventory, version, source/support hashes, byte counts, word counts and all generated hashes match independently computed values.')
    # Unexpected files can otherwise become active instructions or stale guides.
    for pack in ('cursor-project','portable-project'):
        actualpaths={str(p.relative_to(root)) for p in (root/pack).rglob('*') if p.is_file() and '__pycache__' not in p.parts}
        intended={p for p in expected if p.startswith(pack+'/')}
        if actualpaths!=intended:raise PackError('UNEXPECTED_PACK_FILE',str(sorted(actualpaths^intended)))
    results.append('Platform packs contain exactly the intended shipped files; no stale extra instruction or recipe files.')
    markdown={p:b for p,b in expected.items() if p.endswith(('.md','.mdc'))}
    for folder in ('tools','reference'):
        for p in (root/folder).glob('*.md'):markdown[str(p.relative_to(root))]=p.read_bytes()
    for path,payload in markdown.items():check_markdown(root,path,payload)
    results.append(f'{len(markdown)} Markdown/rule files have balanced fences, unique explicit anchors and valid local links, including root documentation.')
    for pack in ('cursor-project','portable-project'):
        for loader in ([f'{pack}/.cursor/rules/10-vandeput-method.mdc'] if pack=='cursor-project' else [f'{pack}/AGENTS.md',f'{pack}/.vandeput/loader.md',f'{pack}/optional-adapters/cline/10-vandeput-method.md']):
            text=expected[loader].decode()
            for ref in set(re.findall(r'\.vandeput/[a-zA-Z0-9_./-]+',text)):
                # The regex captures directory mentions too; validate those as
                # directories instead of assuming an executable target.
                target=root/pack/ref
                if not target.exists():raise PackError('LOADER_TARGET',f'{loader}: {ref}')
        if pack=='cursor-project':
            rule=expected[f'{pack}/.cursor/rules/10-vandeput-method.mdc'].decode()
            if not re.match(r'^---\n.*?\nalwaysApply: true\n---\n',rule,re.S):raise PackError('CURSOR_METADATA','front matter')
            if len(rule.splitlines())>150:raise PackError('LOADER_SIZE','keep the native rule compact')
    cfg=json.loads(expected['portable-project/optional-adapters/opencode/opencode.instructions.example.json'])
    if cfg!={'instructions':['.vandeput/loader.md']}:raise PackError('ADAPTER_CONFIG','OpenCode')
    results.append('Native/optional loader metadata, selective-read targets and integration configurations resolve.')
    registry=json.loads(expected['SOURCE_REGISTER.json']);byid={r['id']:r for r in registry['records']}
    if byid['R04']['origin_id']!='N2-07' or byid['R04']['url']!=byid['N2-07']['url'] or byid['R04']['assets']!=byid['N2-07']['assets']:
        raise PackError('SOURCE_ALIAS','R04 must remain the N2-07 duplicate')
    if any(r.get('executed') for r in registry['records']):raise PackError('SOURCE_EXECUTION_CLAIM','no supplied source was executed in this release')
    for r in registry['records']:
        for asset in r['assets']:
            if not re.fullmatch(r'[0-9a-f]{64}',asset['sha256']) or asset['bytes']<1:raise PackError('SOURCE_ASSET',r['id'])
    results.append('Source IDs, duplicate-origin handling, archived asset metadata and no-upstream-execution boundary are consistent.')
    results.append('Behavioral scenarios are specifications. This static success does not establish live host behavior or forecasting/policy performance.')
    return results

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('root',nargs='?',default=str(Path(__file__).resolve().parents[1]));args=parser.parse_args()
    try:results=validate(Path(args.root))
    except PackError as exc:print(f'FAIL [{exc.code}] {exc.detail}',file=sys.stderr);return 1
    except Exception as exc:print(f'ERROR [VALIDATOR_EXCEPTION] {type(exc).__name__}: {exc}',file=sys.stderr);return 2
    for r in results:print('PASS:',r)
    print('STATIC VALIDATION PASSED');return 0
if __name__=='__main__':sys.exit(main())
